pull_request_rules:
  - name: automatic merge to sit when all checks pass
    conditions:
      - base=sit
    actions:
      merge:
        method: merge
      comment:
        message: Thank you for your contribution @{{author}}
      label:
        add:
          - ready-to-master

  - name: automatic merge dev to master
    conditions:
      - base=master
      - label=deploy
    actions:
      merge:
        method: merge
