name: Code Analysis

on:
  push:
    branches:
      - sit
  pull_request:
    branches:
      - sit
      - master
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

#       - name: Set up PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: 8.1
          
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=fairusatoir_web-store-be
            -Dsonar.organization=fairusatoir
            -Dsonar.sources=app
            -Dsonar.tests=tests
            -Dsonar.php.tests.reportPath=junit.xml
            -Dsonar.php.coverage.reportPaths=coverage.xml

      - name: Run tests
        run: php artisan test
