name: SonarCloud Analysis

on:
  push:
    branches:
      - sit
  pull_request:
    branches:
      - sit
      - main
  schedule:
    - cron: "0 1 * * 6"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Run tests
        run: php artisan test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=fairusatoir_web-store-be
            -Dsonar.organization=fairusatoir
            -Dsonar.sources=app,config,database,routes,tests
            -Dsonar.tests=tests
            -Dsonar.php.tests.reportPath=junit.xml
            # -Dsonar.php.coverage.reportPaths=coverage.xml
